repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply # ensures that the configured hooks apply to at least one file in the repository. new in 1.4.0.
      - id: check-useless-excludes # ensures that exclude directives apply to any file in the repository. new in 1.4.0.
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-yaml # Attempts to load all yaml files to verify syntax.
      - id: check-merge-conflict # Check for files that contain merge conflict strings.
      - id: end-of-file-fixer # Makes sure files end in a newline and only a newline.
      - id: trailing-whitespace # Trims trailing whitespace.
        args: [--markdown-linebreak-ext=md]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.4.1
    hooks:
      - id: prettier # See here: https://github.com/prettier/prettier
  - repo: https://github.com/timothycrosley/isort
    rev: 5.9.3 # should be the same as in dev.in
    hooks:
      - id: isort # isort your imports, so you don't have to.
